-- Synthetic auth fixtures for the three seed users from
-- 0001_synthetic_practice.sql. Development/preview/CI only — see
-- docs/product/DIRECTIVE_FREEZE.md §8.
--
-- Plaintext password for ALL three seed users: Synthetic-Practice-Pass-2026!
-- (fine to state plainly here: these are throwaway synthetic accounts that
-- exist only to test the sign-in flow, not real credentials — see
-- docs/security/SECRETS_POLICY.md, which governs real secrets, not
-- disposable fixture data.)
--
-- Hash generated by the actual hashPassword() implementation
-- (apps/api/src/auth/password.ts), not hand-rolled, so it is guaranteed
-- to verify correctly.
UPDATE users
SET password_hash = 'pbkdf2$210000$1fa39db53c7856944407452764792428$7202aca66dd95bf5d9eba0f4d600122292af9b1b289d2da119430d1396da3b07'
WHERE id IN (
  '00000000-0000-0000-0000-0000000000a2', -- Irene A (director, org A)
  '00000000-0000-0000-0000-0000000000a3', -- Reception A (reception_admin, org A)
  '00000000-0000-0000-0000-0000000000b2'  -- Director B (director, org B)
);

-- Irene A (director — a privileged role, see packages/permissions
-- PRIVILEGED_ROLES) has MFA already enrolled and enabled, so signing in
-- as her demonstrates the mfa_required path immediately rather than
-- mfa_setup_required. TOTP secret generated by the actual
-- generateTotpSecret() implementation.
INSERT INTO mfa_secrets (organisation_id, user_id, secret_base32, enabled_at)
VALUES (
  '00000000-0000-0000-0000-000000000001',
  '00000000-0000-0000-0000-0000000000a2',
  'FPJDXC26LNKN4PKEPNK4EZWXPWWCQURS',
  now()
);
